// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coreapp/config/v1/config.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigEvent represents various config-related events in the system.
type ConfigEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A oneof field containing different types of config event data.
	//
	// Types that are valid to be assigned to EventData:
	//
	//	*ConfigEvent_EventUpserted
	EventData     isConfigEvent_EventData `protobuf_oneof:"event_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEvent) Reset() {
	*x = ConfigEvent{}
	mi := &file_coreapp_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEvent) ProtoMessage() {}

func (x *ConfigEvent) ProtoReflect() protoreflect.Message {
	mi := &file_coreapp_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEvent.ProtoReflect.Descriptor instead.
func (*ConfigEvent) Descriptor() ([]byte, []int) {
	return file_coreapp_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigEvent) GetEventData() isConfigEvent_EventData {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *ConfigEvent) GetEventUpserted() *ConfigUpdatedEventData {
	if x != nil {
		if x, ok := x.EventData.(*ConfigEvent_EventUpserted); ok {
			return x.EventUpserted
		}
	}
	return nil
}

type isConfigEvent_EventData interface {
	isConfigEvent_EventData()
}

type ConfigEvent_EventUpserted struct {
	// Event data for when a event is created or updated.
	EventUpserted *ConfigUpdatedEventData `protobuf:"bytes,1,opt,name=eventUpserted,proto3,oneof"`
}

func (*ConfigEvent_EventUpserted) isConfigEvent_EventData() {}

var File_coreapp_config_v1_config_proto protoreflect.FileDescriptor

const file_coreapp_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x1ecoreapp/config/v1/config.proto\x12\x11coreapp.config.v1\x1a\"coreapp/config/v1/event_data.proto\"n\n" +
	"\vConfigEvent\x12Q\n" +
	"\reventUpserted\x18\x01 \x01(\v2).coreapp.config.v1.ConfigUpdatedEventDataH\x00R\reventUpsertedB\f\n" +
	"\n" +
	"event_dataB\xc4\x01\n" +
	"\x15com.coreapp.config.v1B\vConfigProtoP\x01Z8coreapp.com/packages/go/proto/coreapp/config/v1;configv1\xa2\x02\x03CCX\xaa\x02\x11Coreapp.Config.V1\xca\x02\x11Coreapp\\Config\\V1\xe2\x02\x1dCoreapp\\Config\\V1\\GPBMetadata\xea\x02\x13Coreapp::Config::V1b\x06proto3"

var (
	file_coreapp_config_v1_config_proto_rawDescOnce sync.Once
	file_coreapp_config_v1_config_proto_rawDescData []byte
)

func file_coreapp_config_v1_config_proto_rawDescGZIP() []byte {
	file_coreapp_config_v1_config_proto_rawDescOnce.Do(func() {
		file_coreapp_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coreapp_config_v1_config_proto_rawDesc), len(file_coreapp_config_v1_config_proto_rawDesc)))
	})
	return file_coreapp_config_v1_config_proto_rawDescData
}

var file_coreapp_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coreapp_config_v1_config_proto_goTypes = []any{
	(*ConfigEvent)(nil),            // 0: coreapp.config.v1.ConfigEvent
	(*ConfigUpdatedEventData)(nil), // 1: coreapp.config.v1.ConfigUpdatedEventData
}
var file_coreapp_config_v1_config_proto_depIdxs = []int32{
	1, // 0: coreapp.config.v1.ConfigEvent.eventUpserted:type_name -> coreapp.config.v1.ConfigUpdatedEventData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coreapp_config_v1_config_proto_init() }
func file_coreapp_config_v1_config_proto_init() {
	if File_coreapp_config_v1_config_proto != nil {
		return
	}
	file_coreapp_config_v1_event_data_proto_init()
	file_coreapp_config_v1_config_proto_msgTypes[0].OneofWrappers = []any{
		(*ConfigEvent_EventUpserted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coreapp_config_v1_config_proto_rawDesc), len(file_coreapp_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coreapp_config_v1_config_proto_goTypes,
		DependencyIndexes: file_coreapp_config_v1_config_proto_depIdxs,
		MessageInfos:      file_coreapp_config_v1_config_proto_msgTypes,
	}.Build()
	File_coreapp_config_v1_config_proto = out.File
	file_coreapp_config_v1_config_proto_goTypes = nil
	file_coreapp_config_v1_config_proto_depIdxs = nil
}
