// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coreapp/domain/v1/domain.proto

package domainv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DomainEvent represents various domain-related events in the system.
type DomainEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A oneof field containing different types of domain event data.
	//
	// Types that are valid to be assigned to EventData:
	//
	//	*DomainEvent_DomainUpserted
	EventData     isDomainEvent_EventData `protobuf_oneof:"event_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainEvent) Reset() {
	*x = DomainEvent{}
	mi := &file_coreapp_domain_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEvent) ProtoMessage() {}

func (x *DomainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_coreapp_domain_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEvent.ProtoReflect.Descriptor instead.
func (*DomainEvent) Descriptor() ([]byte, []int) {
	return file_coreapp_domain_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *DomainEvent) GetEventData() isDomainEvent_EventData {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *DomainEvent) GetDomainUpserted() *DomainUpdatedEventData {
	if x != nil {
		if x, ok := x.EventData.(*DomainEvent_DomainUpserted); ok {
			return x.DomainUpserted
		}
	}
	return nil
}

type isDomainEvent_EventData interface {
	isDomainEvent_EventData()
}

type DomainEvent_DomainUpserted struct {
	// Event data for when a domain is created or updated.
	DomainUpserted *DomainUpdatedEventData `protobuf:"bytes,1,opt,name=domainUpserted,proto3,oneof"`
}

func (*DomainEvent_DomainUpserted) isDomainEvent_EventData() {}

var File_coreapp_domain_v1_domain_proto protoreflect.FileDescriptor

const file_coreapp_domain_v1_domain_proto_rawDesc = "" +
	"\n" +
	"\x1ecoreapp/domain/v1/domain.proto\x12\x11coreapp.domain.v1\x1a\"coreapp/domain/v1/event_data.proto\"p\n" +
	"\vDomainEvent\x12S\n" +
	"\x0edomainUpserted\x18\x01 \x01(\v2).coreapp.domain.v1.DomainUpdatedEventDataH\x00R\x0edomainUpsertedB\f\n" +
	"\n" +
	"event_dataB\xc4\x01\n" +
	"\x15com.coreapp.domain.v1B\vDomainProtoP\x01Z8coreapp.com/packages/go/proto/coreapp/domain/v1;domainv1\xa2\x02\x03CDX\xaa\x02\x11Coreapp.Domain.V1\xca\x02\x11Coreapp\\Domain\\V1\xe2\x02\x1dCoreapp\\Domain\\V1\\GPBMetadata\xea\x02\x13Coreapp::Domain::V1b\x06proto3"

var (
	file_coreapp_domain_v1_domain_proto_rawDescOnce sync.Once
	file_coreapp_domain_v1_domain_proto_rawDescData []byte
)

func file_coreapp_domain_v1_domain_proto_rawDescGZIP() []byte {
	file_coreapp_domain_v1_domain_proto_rawDescOnce.Do(func() {
		file_coreapp_domain_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coreapp_domain_v1_domain_proto_rawDesc), len(file_coreapp_domain_v1_domain_proto_rawDesc)))
	})
	return file_coreapp_domain_v1_domain_proto_rawDescData
}

var file_coreapp_domain_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coreapp_domain_v1_domain_proto_goTypes = []any{
	(*DomainEvent)(nil),            // 0: coreapp.domain.v1.DomainEvent
	(*DomainUpdatedEventData)(nil), // 1: coreapp.domain.v1.DomainUpdatedEventData
}
var file_coreapp_domain_v1_domain_proto_depIdxs = []int32{
	1, // 0: coreapp.domain.v1.DomainEvent.domainUpserted:type_name -> coreapp.domain.v1.DomainUpdatedEventData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coreapp_domain_v1_domain_proto_init() }
func file_coreapp_domain_v1_domain_proto_init() {
	if File_coreapp_domain_v1_domain_proto != nil {
		return
	}
	file_coreapp_domain_v1_event_data_proto_init()
	file_coreapp_domain_v1_domain_proto_msgTypes[0].OneofWrappers = []any{
		(*DomainEvent_DomainUpserted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coreapp_domain_v1_domain_proto_rawDesc), len(file_coreapp_domain_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coreapp_domain_v1_domain_proto_goTypes,
		DependencyIndexes: file_coreapp_domain_v1_domain_proto_depIdxs,
		MessageInfos:      file_coreapp_domain_v1_domain_proto_msgTypes,
	}.Build()
	File_coreapp_domain_v1_domain_proto = out.File
	file_coreapp_domain_v1_domain_proto_goTypes = nil
	file_coreapp_domain_v1_domain_proto_depIdxs = nil
}
