// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coreapp/event/v1/event.proto

package eventv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEvent represents various event-related events in the system.
type EventEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A oneof field containing different types of event event data.
	//
	// Types that are valid to be assigned to EventData:
	//
	//	*EventEvent_EventUpserted
	EventData     isEventEvent_EventData `protobuf_oneof:"event_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEvent) Reset() {
	*x = EventEvent{}
	mi := &file_coreapp_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEvent) ProtoMessage() {}

func (x *EventEvent) ProtoReflect() protoreflect.Message {
	mi := &file_coreapp_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEvent.ProtoReflect.Descriptor instead.
func (*EventEvent) Descriptor() ([]byte, []int) {
	return file_coreapp_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventEvent) GetEventData() isEventEvent_EventData {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *EventEvent) GetEventUpserted() *EventUpdatedEventData {
	if x != nil {
		if x, ok := x.EventData.(*EventEvent_EventUpserted); ok {
			return x.EventUpserted
		}
	}
	return nil
}

type isEventEvent_EventData interface {
	isEventEvent_EventData()
}

type EventEvent_EventUpserted struct {
	// Event data for when a event is created or updated.
	EventUpserted *EventUpdatedEventData `protobuf:"bytes,1,opt,name=eventUpserted,proto3,oneof"`
}

func (*EventEvent_EventUpserted) isEventEvent_EventData() {}

var File_coreapp_event_v1_event_proto protoreflect.FileDescriptor

const file_coreapp_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1ccoreapp/event/v1/event.proto\x12\x10coreapp.event.v1\x1a!coreapp/event/v1/event_data.proto\"k\n" +
	"\n" +
	"EventEvent\x12O\n" +
	"\reventUpserted\x18\x01 \x01(\v2'.coreapp.event.v1.EventUpdatedEventDataH\x00R\reventUpsertedB\f\n" +
	"\n" +
	"event_dataB\xbc\x01\n" +
	"\x14com.coreapp.event.v1B\n" +
	"EventProtoP\x01Z6coreapp.com/packages/go/proto/coreapp/event/v1;eventv1\xa2\x02\x03CEX\xaa\x02\x10Coreapp.Event.V1\xca\x02\x10Coreapp\\Event\\V1\xe2\x02\x1cCoreapp\\Event\\V1\\GPBMetadata\xea\x02\x12Coreapp::Event::V1b\x06proto3"

var (
	file_coreapp_event_v1_event_proto_rawDescOnce sync.Once
	file_coreapp_event_v1_event_proto_rawDescData []byte
)

func file_coreapp_event_v1_event_proto_rawDescGZIP() []byte {
	file_coreapp_event_v1_event_proto_rawDescOnce.Do(func() {
		file_coreapp_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coreapp_event_v1_event_proto_rawDesc), len(file_coreapp_event_v1_event_proto_rawDesc)))
	})
	return file_coreapp_event_v1_event_proto_rawDescData
}

var file_coreapp_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coreapp_event_v1_event_proto_goTypes = []any{
	(*EventEvent)(nil),            // 0: coreapp.event.v1.EventEvent
	(*EventUpdatedEventData)(nil), // 1: coreapp.event.v1.EventUpdatedEventData
}
var file_coreapp_event_v1_event_proto_depIdxs = []int32{
	1, // 0: coreapp.event.v1.EventEvent.eventUpserted:type_name -> coreapp.event.v1.EventUpdatedEventData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coreapp_event_v1_event_proto_init() }
func file_coreapp_event_v1_event_proto_init() {
	if File_coreapp_event_v1_event_proto != nil {
		return
	}
	file_coreapp_event_v1_event_data_proto_init()
	file_coreapp_event_v1_event_proto_msgTypes[0].OneofWrappers = []any{
		(*EventEvent_EventUpserted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coreapp_event_v1_event_proto_rawDesc), len(file_coreapp_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coreapp_event_v1_event_proto_goTypes,
		DependencyIndexes: file_coreapp_event_v1_event_proto_depIdxs,
		MessageInfos:      file_coreapp_event_v1_event_proto_msgTypes,
	}.Build()
	File_coreapp_event_v1_event_proto = out.File
	file_coreapp_event_v1_event_proto_goTypes = nil
	file_coreapp_event_v1_event_proto_depIdxs = nil
}
