// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coreapp/event/v1/event_data.proto

package eventv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventUpdatedEventData represents when a event's configuration has been updated
type EventUpdatedEventData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of affected event IDs
	Id            []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventUpdatedEventData) Reset() {
	*x = EventUpdatedEventData{}
	mi := &file_coreapp_event_v1_event_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdatedEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdatedEventData) ProtoMessage() {}

func (x *EventUpdatedEventData) ProtoReflect() protoreflect.Message {
	mi := &file_coreapp_event_v1_event_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventUpdatedEventData.ProtoReflect.Descriptor instead.
func (*EventUpdatedEventData) Descriptor() ([]byte, []int) {
	return file_coreapp_event_v1_event_data_proto_rawDescGZIP(), []int{0}
}

func (x *EventUpdatedEventData) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_coreapp_event_v1_event_data_proto protoreflect.FileDescriptor

const file_coreapp_event_v1_event_data_proto_rawDesc = "" +
	"\n" +
	"!coreapp/event/v1/event_data.proto\x12\x10coreapp.event.v1\"'\n" +
	"\x15EventUpdatedEventData\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\tR\x02idB\xc0\x01\n" +
	"\x14com.coreapp.event.v1B\x0eEventDataProtoP\x01Z6coreapp.com/packages/go/proto/coreapp/event/v1;eventv1\xa2\x02\x03CEX\xaa\x02\x10Coreapp.Event.V1\xca\x02\x10Coreapp\\Event\\V1\xe2\x02\x1cCoreapp\\Event\\V1\\GPBMetadata\xea\x02\x12Coreapp::Event::V1b\x06proto3"

var (
	file_coreapp_event_v1_event_data_proto_rawDescOnce sync.Once
	file_coreapp_event_v1_event_data_proto_rawDescData []byte
)

func file_coreapp_event_v1_event_data_proto_rawDescGZIP() []byte {
	file_coreapp_event_v1_event_data_proto_rawDescOnce.Do(func() {
		file_coreapp_event_v1_event_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coreapp_event_v1_event_data_proto_rawDesc), len(file_coreapp_event_v1_event_data_proto_rawDesc)))
	})
	return file_coreapp_event_v1_event_data_proto_rawDescData
}

var file_coreapp_event_v1_event_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coreapp_event_v1_event_data_proto_goTypes = []any{
	(*EventUpdatedEventData)(nil), // 0: coreapp.event.v1.EventUpdatedEventData
}
var file_coreapp_event_v1_event_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coreapp_event_v1_event_data_proto_init() }
func file_coreapp_event_v1_event_data_proto_init() {
	if File_coreapp_event_v1_event_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coreapp_event_v1_event_data_proto_rawDesc), len(file_coreapp_event_v1_event_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coreapp_event_v1_event_data_proto_goTypes,
		DependencyIndexes: file_coreapp_event_v1_event_data_proto_depIdxs,
		MessageInfos:      file_coreapp_event_v1_event_data_proto_msgTypes,
	}.Build()
	File_coreapp_event_v1_event_data_proto = out.File
	file_coreapp_event_v1_event_data_proto_goTypes = nil
	file_coreapp_event_v1_event_data_proto_depIdxs = nil
}
