apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSchema
metadata:
  name: coreapp-domain-v1-domainevent
spec:
  type: PROTOCOL_BUFFER
  definition: |
    syntax = "proto2";
    message DomainEvent {
      oneof event_data {
        Inline_coreapp_domain_v1_DomainUpdatedEventData domainUpserted = 1;
      }
      message Inline_coreapp_domain_v1_DomainUpdatedEventData {
        repeated string id = 1;
      }
    }
    